name: Build and Test

jobs:
  build:
    name: Build
    steps:
      - name: Build Binary
        # need to add workspace/
        run: |
          echo "=== Building ==="
          go build -v -o demo .
          echo "✅ Build successful"
          mkdir -p /workspace/artifacts
          cp demo /workspace/artifacts/demo-binary
          echo "Build: $(date)" > /workspace/artifacts/build-info.txt
          ls -lh /workspace/artifacts/
  
  test:
    name: Test
    needs: [build]
    steps:
      - name: Run Tests
        run: |
          echo "=== Running Tests ==="
          go test -v -coverprofile=/workspace/coverage.out ./...
          echo "✅ Tests complete"
          mkdir -p /workspace/artifacts
          cp /workspace/coverage.out /workspace/artifacts/
          echo "Tests passed: $(date)" > /workspace/artifacts/test-report.txt
          ls -lh /workspace/artifacts/