// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/runner.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerName    string                 `protobuf:"bytes,1,opt,name=runner_name,json=runnerName,proto3" json:"runner_name,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"` // e.g., ["docker", "linux", "x64"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerRequest) Reset() {
	*x = RegisterRunnerRequest{}
	mi := &file_proto_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerRequest) ProtoMessage() {}

func (x *RegisterRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerRequest.ProtoReflect.Descriptor instead.
func (*RegisterRunnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRunnerRequest) GetRunnerName() string {
	if x != nil {
		return x.RunnerName
	}
	return ""
}

func (x *RegisterRunnerRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRunnerResponse) Reset() {
	*x = RegisterRunnerResponse{}
	mi := &file_proto_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRunnerResponse) ProtoMessage() {}

func (x *RegisterRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRunnerResponse.ProtoReflect.Descriptor instead.
func (*RegisterRunnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRunnerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"` // e.g., ["docker", "linux", "x64"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *HeartbeatRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LeaseJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"` // e.g., ["docker", "linux", "x64"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseJobRequest) Reset() {
	*x = LeaseJobRequest{}
	mi := &file_proto_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseJobRequest) ProtoMessage() {}

func (x *LeaseJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseJobRequest.ProtoReflect.Descriptor instead.
func (*LeaseJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{4}
}

func (x *LeaseJobRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *LeaseJobRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type LeaseJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// if no job is available, has_job is false and job_spec is empty
	HasJob        bool     `protobuf:"varint,1,opt,name=has_job,json=hasJob,proto3" json:"has_job,omitempty"`
	JobSpec       *JobSpec `protobuf:"bytes,2,opt,name=job_spec,json=jobSpec,proto3" json:"job_spec,omitempty"` // present if has_job is true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseJobResponse) Reset() {
	*x = LeaseJobResponse{}
	mi := &file_proto_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseJobResponse) ProtoMessage() {}

func (x *LeaseJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseJobResponse.ProtoReflect.Descriptor instead.
func (*LeaseJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{5}
}

func (x *LeaseJobResponse) GetHasJob() bool {
	if x != nil {
		return x.HasJob
	}
	return false
}

func (x *LeaseJobResponse) GetJobSpec() *JobSpec {
	if x != nil {
		return x.JobSpec
	}
	return nil
}

type JobSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	JobId     string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RunId     string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Repo      string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Ref       string                 `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"` // branch or tag
	CommitSha string                 `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	JobName   string                 `protobuf:"bytes,6,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Steps     []*StepSpec            `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	// optional: environment variables, secrets, etc.
	ContainerImage string `protobuf:"bytes,8,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"` // e.g., "ubuntu:20.04"
	RepoPath       string `protobuf:"bytes,9,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_proto_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{6}
}

func (x *JobSpec) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSpec) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobSpec) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *JobSpec) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *JobSpec) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *JobSpec) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobSpec) GetSteps() []*StepSpec {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *JobSpec) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *JobSpec) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

type StepSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // e.g., "make test"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepSpec) Reset() {
	*x = StepSpec{}
	mi := &file_proto_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepSpec) ProtoMessage() {}

func (x *StepSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepSpec.ProtoReflect.Descriptor instead.
func (*StepSpec) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{7}
}

func (x *StepSpec) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RunnerEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RunnerId string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	JobId    string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunnerEvent_StepStarted
	//	*RunnerEvent_LongChunk
	//	*RunnerEvent_StepFinished
	//	*RunnerEvent_JobFinished
	Event         isRunnerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerEvent) Reset() {
	*x = RunnerEvent{}
	mi := &file_proto_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerEvent) ProtoMessage() {}

func (x *RunnerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerEvent.ProtoReflect.Descriptor instead.
func (*RunnerEvent) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{8}
}

func (x *RunnerEvent) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RunnerEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunnerEvent) GetEvent() isRunnerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunnerEvent) GetStepStarted() *StepStarted {
	if x != nil {
		if x, ok := x.Event.(*RunnerEvent_StepStarted); ok {
			return x.StepStarted
		}
	}
	return nil
}

func (x *RunnerEvent) GetLongChunk() *LongChunk {
	if x != nil {
		if x, ok := x.Event.(*RunnerEvent_LongChunk); ok {
			return x.LongChunk
		}
	}
	return nil
}

func (x *RunnerEvent) GetStepFinished() *StepFinished {
	if x != nil {
		if x, ok := x.Event.(*RunnerEvent_StepFinished); ok {
			return x.StepFinished
		}
	}
	return nil
}

func (x *RunnerEvent) GetJobFinished() *JobFinished {
	if x != nil {
		if x, ok := x.Event.(*RunnerEvent_JobFinished); ok {
			return x.JobFinished
		}
	}
	return nil
}

type isRunnerEvent_Event interface {
	isRunnerEvent_Event()
}

type RunnerEvent_StepStarted struct {
	StepStarted *StepStarted `protobuf:"bytes,10,opt,name=step_started,json=stepStarted,proto3,oneof"`
}

type RunnerEvent_LongChunk struct {
	LongChunk *LongChunk `protobuf:"bytes,11,opt,name=long_chunk,json=longChunk,proto3,oneof"`
}

type RunnerEvent_StepFinished struct {
	StepFinished *StepFinished `protobuf:"bytes,12,opt,name=step_finished,json=stepFinished,proto3,oneof"`
}

type RunnerEvent_JobFinished struct {
	JobFinished *JobFinished `protobuf:"bytes,13,opt,name=job_finished,json=jobFinished,proto3,oneof"`
}

func (*RunnerEvent_StepStarted) isRunnerEvent_Event() {}

func (*RunnerEvent_LongChunk) isRunnerEvent_Event() {}

func (*RunnerEvent_StepFinished) isRunnerEvent_Event() {}

func (*RunnerEvent_JobFinished) isRunnerEvent_Event() {}

type StepStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,2,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"` // timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStarted) Reset() {
	*x = StepStarted{}
	mi := &file_proto_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStarted) ProtoMessage() {}

func (x *StepStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStarted.ProtoReflect.Descriptor instead.
func (*StepStarted) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{9}
}

func (x *StepStarted) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepStarted) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type LongChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`          // 0 if unknown/not applicable
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // log data chunk
	TsUnixMs      int64                  `protobuf:"varint,3,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"` // timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongChunk) Reset() {
	*x = LongChunk{}
	mi := &file_proto_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongChunk) ProtoMessage() {}

func (x *LongChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongChunk.ProtoReflect.Descriptor instead.
func (*LongChunk) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{10}
}

func (x *LongChunk) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *LongChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LongChunk) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type StepFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`            // 0 for success, non-zero for failure
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                 // "success" or "failure"
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // optional error message
	TsUnixMs      int64                  `protobuf:"varint,5,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`          // timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepFinished) Reset() {
	*x = StepFinished{}
	mi := &file_proto_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFinished) ProtoMessage() {}

func (x *StepFinished) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFinished.ProtoReflect.Descriptor instead.
func (*StepFinished) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{11}
}

func (x *StepFinished) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepFinished) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StepFinished) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepFinished) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StepFinished) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type JobFinished struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string job_id = 1;
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                 // "success" or "failure"
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // optional error message
	TsUnixMs      int64  `protobuf:"varint,3,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`          // timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFinished) Reset() {
	*x = JobFinished{}
	mi := &file_proto_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFinished) ProtoMessage() {}

func (x *JobFinished) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFinished.ProtoReflect.Descriptor instead.
func (*JobFinished) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{12}
}

func (x *JobFinished) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobFinished) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobFinished) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_proto_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_proto_runner_proto_rawDescGZIP(), []int{13}
}

func (x *ReportAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_runner_proto protoreflect.FileDescriptor

const file_proto_runner_proto_rawDesc = "" +
	"\n" +
	"\x12proto/runner.proto\x12\trunner.v1\"P\n" +
	"\x15RegisterRunnerRequest\x12\x1f\n" +
	"\vrunner_name\x18\x01 \x01(\tR\n" +
	"runnerName\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\"(\n" +
	"\x16RegisterRunnerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"G\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"F\n" +
	"\x0fLeaseJobRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\"Z\n" +
	"\x10LeaseJobResponse\x12\x17\n" +
	"\ahas_job\x18\x01 \x01(\bR\x06hasJob\x12-\n" +
	"\bjob_spec\x18\x02 \x01(\v2\x12.runner.v1.JobSpecR\ajobSpec\"\x88\x02\n" +
	"\aJobSpec\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x10\n" +
	"\x03ref\x18\x04 \x01(\tR\x03ref\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha\x12\x19\n" +
	"\bjob_name\x18\x06 \x01(\tR\ajobName\x12)\n" +
	"\x05steps\x18\a \x03(\v2\x13.runner.v1.StepSpecR\x05steps\x12'\n" +
	"\x0fcontainer_image\x18\b \x01(\tR\x0econtainerImage\x12\x1b\n" +
	"\trepo_path\x18\t \x01(\tR\brepoPath\"Q\n" +
	"\bStepSpec\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"\xbb\x02\n" +
	"\vRunnerEvent\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12;\n" +
	"\fstep_started\x18\n" +
	" \x01(\v2\x16.runner.v1.StepStartedH\x00R\vstepStarted\x125\n" +
	"\n" +
	"long_chunk\x18\v \x01(\v2\x14.runner.v1.LongChunkH\x00R\tlongChunk\x12>\n" +
	"\rstep_finished\x18\f \x01(\v2\x17.runner.v1.StepFinishedH\x00R\fstepFinished\x12;\n" +
	"\fjob_finished\x18\r \x01(\v2\x16.runner.v1.JobFinishedH\x00R\vjobFinishedB\a\n" +
	"\x05event\"D\n" +
	"\vStepStarted\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x02 \x01(\x03R\btsUnixMs\"\\\n" +
	"\tLongChunk\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x03 \x01(\x03R\btsUnixMs\"\x9f\x01\n" +
	"\fStepFinished\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x05 \x01(\x03R\btsUnixMs\"h\n" +
	"\vJobFinished\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x03 \x01(\x03R\btsUnixMs\"\x1b\n" +
	"\tReportAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb2\x02\n" +
	"\rRunnerGateway\x12U\n" +
	"\x0eRegisterRunner\x12 .runner.v1.RegisterRunnerRequest\x1a!.runner.v1.RegisterRunnerResponse\x12C\n" +
	"\bLeaseJob\x12\x1a.runner.v1.LeaseJobRequest\x1a\x1b.runner.v1.LeaseJobResponse\x12=\n" +
	"\vReportEvent\x12\x16.runner.v1.RunnerEvent\x1a\x14.runner.v1.ReportAck(\x01\x12F\n" +
	"\tHeartbeat\x12\x1b.runner.v1.HeartbeatRequest\x1a\x1c.runner.v1.HeartbeatResponseB*Z(ci-platform/control-plane/proto/runnerpbb\x06proto3"

var (
	file_proto_runner_proto_rawDescOnce sync.Once
	file_proto_runner_proto_rawDescData []byte
)

func file_proto_runner_proto_rawDescGZIP() []byte {
	file_proto_runner_proto_rawDescOnce.Do(func() {
		file_proto_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_runner_proto_rawDesc), len(file_proto_runner_proto_rawDesc)))
	})
	return file_proto_runner_proto_rawDescData
}

var file_proto_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_runner_proto_goTypes = []any{
	(*RegisterRunnerRequest)(nil),  // 0: runner.v1.RegisterRunnerRequest
	(*RegisterRunnerResponse)(nil), // 1: runner.v1.RegisterRunnerResponse
	(*HeartbeatRequest)(nil),       // 2: runner.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 3: runner.v1.HeartbeatResponse
	(*LeaseJobRequest)(nil),        // 4: runner.v1.LeaseJobRequest
	(*LeaseJobResponse)(nil),       // 5: runner.v1.LeaseJobResponse
	(*JobSpec)(nil),                // 6: runner.v1.JobSpec
	(*StepSpec)(nil),               // 7: runner.v1.StepSpec
	(*RunnerEvent)(nil),            // 8: runner.v1.RunnerEvent
	(*StepStarted)(nil),            // 9: runner.v1.StepStarted
	(*LongChunk)(nil),              // 10: runner.v1.LongChunk
	(*StepFinished)(nil),           // 11: runner.v1.StepFinished
	(*JobFinished)(nil),            // 12: runner.v1.JobFinished
	(*ReportAck)(nil),              // 13: runner.v1.ReportAck
}
var file_proto_runner_proto_depIdxs = []int32{
	6,  // 0: runner.v1.LeaseJobResponse.job_spec:type_name -> runner.v1.JobSpec
	7,  // 1: runner.v1.JobSpec.steps:type_name -> runner.v1.StepSpec
	9,  // 2: runner.v1.RunnerEvent.step_started:type_name -> runner.v1.StepStarted
	10, // 3: runner.v1.RunnerEvent.long_chunk:type_name -> runner.v1.LongChunk
	11, // 4: runner.v1.RunnerEvent.step_finished:type_name -> runner.v1.StepFinished
	12, // 5: runner.v1.RunnerEvent.job_finished:type_name -> runner.v1.JobFinished
	0,  // 6: runner.v1.RunnerGateway.RegisterRunner:input_type -> runner.v1.RegisterRunnerRequest
	4,  // 7: runner.v1.RunnerGateway.LeaseJob:input_type -> runner.v1.LeaseJobRequest
	8,  // 8: runner.v1.RunnerGateway.ReportEvent:input_type -> runner.v1.RunnerEvent
	2,  // 9: runner.v1.RunnerGateway.Heartbeat:input_type -> runner.v1.HeartbeatRequest
	1,  // 10: runner.v1.RunnerGateway.RegisterRunner:output_type -> runner.v1.RegisterRunnerResponse
	5,  // 11: runner.v1.RunnerGateway.LeaseJob:output_type -> runner.v1.LeaseJobResponse
	13, // 12: runner.v1.RunnerGateway.ReportEvent:output_type -> runner.v1.ReportAck
	3,  // 13: runner.v1.RunnerGateway.Heartbeat:output_type -> runner.v1.HeartbeatResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_runner_proto_init() }
func file_proto_runner_proto_init() {
	if File_proto_runner_proto != nil {
		return
	}
	file_proto_runner_proto_msgTypes[8].OneofWrappers = []any{
		(*RunnerEvent_StepStarted)(nil),
		(*RunnerEvent_LongChunk)(nil),
		(*RunnerEvent_StepFinished)(nil),
		(*RunnerEvent_JobFinished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_runner_proto_rawDesc), len(file_proto_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runner_proto_goTypes,
		DependencyIndexes: file_proto_runner_proto_depIdxs,
		MessageInfos:      file_proto_runner_proto_msgTypes,
	}.Build()
	File_proto_runner_proto = out.File
	file_proto_runner_proto_goTypes = nil
	file_proto_runner_proto_depIdxs = nil
}
