// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: runner.proto

package runnerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerGateway_RegisterRunner_FullMethodName = "/runner.v1.RunnerGateway/RegisterRunner"
	RunnerGateway_LeaseJob_FullMethodName       = "/runner.v1.RunnerGateway/LeaseJob"
	RunnerGateway_ReportEvent_FullMethodName    = "/runner.v1.RunnerGateway/ReportEvent"
	RunnerGateway_Heartbeat_FullMethodName      = "/runner.v1.RunnerGateway/Heartbeat"
)

// RunnerGatewayClient is the client API for RunnerGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerGatewayClient interface {
	RegisterRunner(ctx context.Context, in *RegisterRunnerRequest, opts ...grpc.CallOption) (*RegisterRunnerResponse, error)
	LeaseJob(ctx context.Context, in *LeaseJobRequest, opts ...grpc.CallOption) (*LeaseJobResponse, error)
	ReportEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunnerEvent, ReportAck], error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type runnerGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerGatewayClient(cc grpc.ClientConnInterface) RunnerGatewayClient {
	return &runnerGatewayClient{cc}
}

func (c *runnerGatewayClient) RegisterRunner(ctx context.Context, in *RegisterRunnerRequest, opts ...grpc.CallOption) (*RegisterRunnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRunnerResponse)
	err := c.cc.Invoke(ctx, RunnerGateway_RegisterRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerGatewayClient) LeaseJob(ctx context.Context, in *LeaseJobRequest, opts ...grpc.CallOption) (*LeaseJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseJobResponse)
	err := c.cc.Invoke(ctx, RunnerGateway_LeaseJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerGatewayClient) ReportEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunnerEvent, ReportAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerGateway_ServiceDesc.Streams[0], RunnerGateway_ReportEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunnerEvent, ReportAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerGateway_ReportEventClient = grpc.ClientStreamingClient[RunnerEvent, ReportAck]

func (c *runnerGatewayClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, RunnerGateway_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerGatewayServer is the server API for RunnerGateway service.
// All implementations must embed UnimplementedRunnerGatewayServer
// for forward compatibility.
type RunnerGatewayServer interface {
	RegisterRunner(context.Context, *RegisterRunnerRequest) (*RegisterRunnerResponse, error)
	LeaseJob(context.Context, *LeaseJobRequest) (*LeaseJobResponse, error)
	ReportEvent(grpc.ClientStreamingServer[RunnerEvent, ReportAck]) error
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedRunnerGatewayServer()
}

// UnimplementedRunnerGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerGatewayServer struct{}

func (UnimplementedRunnerGatewayServer) RegisterRunner(context.Context, *RegisterRunnerRequest) (*RegisterRunnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRunner not implemented")
}
func (UnimplementedRunnerGatewayServer) LeaseJob(context.Context, *LeaseJobRequest) (*LeaseJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseJob not implemented")
}
func (UnimplementedRunnerGatewayServer) ReportEvent(grpc.ClientStreamingServer[RunnerEvent, ReportAck]) error {
	return status.Error(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedRunnerGatewayServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRunnerGatewayServer) mustEmbedUnimplementedRunnerGatewayServer() {}
func (UnimplementedRunnerGatewayServer) testEmbeddedByValue()                       {}

// UnsafeRunnerGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerGatewayServer will
// result in compilation errors.
type UnsafeRunnerGatewayServer interface {
	mustEmbedUnimplementedRunnerGatewayServer()
}

func RegisterRunnerGatewayServer(s grpc.ServiceRegistrar, srv RunnerGatewayServer) {
	// If the following call panics, it indicates UnimplementedRunnerGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerGateway_ServiceDesc, srv)
}

func _RunnerGateway_RegisterRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerGatewayServer).RegisterRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerGateway_RegisterRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerGatewayServer).RegisterRunner(ctx, req.(*RegisterRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerGateway_LeaseJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerGatewayServer).LeaseJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerGateway_LeaseJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerGatewayServer).LeaseJob(ctx, req.(*LeaseJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerGateway_ReportEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerGatewayServer).ReportEvent(&grpc.GenericServerStream[RunnerEvent, ReportAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerGateway_ReportEventServer = grpc.ClientStreamingServer[RunnerEvent, ReportAck]

func _RunnerGateway_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerGatewayServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerGateway_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerGatewayServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerGateway_ServiceDesc is the grpc.ServiceDesc for RunnerGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.v1.RunnerGateway",
	HandlerType: (*RunnerGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRunner",
			Handler:    _RunnerGateway_RegisterRunner_Handler,
		},
		{
			MethodName: "LeaseJob",
			Handler:    _RunnerGateway_LeaseJob_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _RunnerGateway_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportEvent",
			Handler:       _RunnerGateway_ReportEvent_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "runner.proto",
}
